-- VHDL Entity Cursor.comparator_inf_8.interface
--
-- Created:
--          by - Julie.UNKNOWN (LAPTOP-J400VU4F)
--          at - 13:19:28 17.12.2021
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.2 (Build 5)
--
LIBRARY ieee;
  USE ieee.std_logic_1164.all;
  USE ieee.numeric_std.all;
LIBRARY gates;
USE gates.gates.all;

ENTITY comparator_inf_8 IS
   PORT( 
      q1    : IN     std_ulogic_vector (5 DOWNTO 0);
      dbus0 : OUT    std_ulogic_vector (5 DOWNTO 0)
   );

-- Declarations

END comparator_inf_8 ;

--
-- VHDL Architecture Cursor.comparator_inf_8.struct
--
-- Created:
--          by - Julie.UNKNOWN (LAPTOP-J400VU4F)
--          at - 13:19:28 17.12.2021
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.2 (Build 5)
--
LIBRARY ieee;
  USE ieee.std_logic_1164.all;
  USE ieee.numeric_std.all;
LIBRARY gates;
USE gates.gates.all;


ARCHITECTURE struct OF comparator_inf_8 IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL in0  : std_logic_vector(5 DOWNTO 0);
   SIGNAL out1 : std_uLogic;


   -- Component Declarations
   COMPONENT mux2to1ULogicVector
   GENERIC (
      dataBitNb : positive := 8;
      delay     : time     := gateDelay
   );
   PORT (
      in0    : IN     std_uLogic_vector (dataBitNb-1 DOWNTO 0);
      in1    : IN     std_uLogic_vector (dataBitNb-1 DOWNTO 0);
      sel    : IN     std_uLogic ;
      muxOut : OUT    std_uLogic_vector (dataBitNb-1 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT or3
   GENERIC (
      delay : time := gateDelay
   );
   PORT (
      in1  : IN     std_uLogic ;
      in2  : IN     std_uLogic ;
      in3  : IN     std_uLogic ;
      out1 : OUT    std_uLogic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : mux2to1ULogicVector USE ENTITY gates.mux2to1ULogicVector;
   FOR ALL : or3 USE ENTITY gates.or3;
   -- pragma synthesis_on


BEGIN
   -- Architecture concurrent statements
   -- HDL Embedded Text Block 1 eb1
   -- eb1 1               
   in0<="001000";                         


   -- Instance port mappings.
   U_1 : mux2to1ULogicVector
      GENERIC MAP (
         dataBitNb => 6,
         delay     => gateDelay
      )
      PORT MAP (
         in0    => in0,
         in1    => q1,
         sel    => out1,
         muxOut => dbus0
      );
   U_0 : or3
      GENERIC MAP (
         delay => gateDelay
      )
      PORT MAP (
         in1  => q1(3),
         in2  => q1(2),
         in3  => q1(1),
         out1 => out1
      );

END struct;
